name: "Validate Application Lists"
on: 
  push:
    paths:
      - "arr-services.json"
      - "other-helpful-apps.json"
      - "app-list-schema.json"

jobs:
  validate-arr-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dsanders11/json-schema-validate-action@v2.1.0
        with:
          schema: ./app-list-schema.json
          files: ./arr-services.json

      - name: Ensure formatting
        run: jq --tab '.' arr-services.json | diff - arr-services.json

  validate-other-apps-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dsanders11/json-schema-validate-action@v2.1.0
        with:
          schema: ./app-list-schema.json
          files: ./other-helpful-apps.json

      - name: Ensure formatting
        run: jq --tab '.' other-helpful-apps.json | diff - other-helpful-apps.json
